Repository Link-zip/Link-zip-BE, pull requests merged in 2024-07, with the labels that each got.

#3 [#2] Feat: 데이터베이스 연결 및 config 설정
  .DS_Store
  config/db.config.js
  index.js
  package-lock.json
  package.json
Labels: ✏️ FEAT

#5 [#4] Chore: 디렉토리 구조 세팅
  src/controllers/temp.txt
  src/dtos/temp.txt
  src/models/temp.txt
  src/routes/temp.txt
  src/services/temp.txt
Labels: 📎 CHORE

#10 [#9] FEAT: 미열람 링크 리스트 조회 구현
  index.js
  package-lock.json
  src/controllers/list.controller.js
  src/dtos/list.dto.js
  src/models/list.dao.js
  src/models/list.sql.js
  src/providers/list.provider.js
  src/routes/list.route.js
  swagger/unsightlist.swagger.yml
Labels: ✏️ FEAT

#12 [#8] Feat: User 테이블 구현, 절대경로 설정
  .DS_Store
  babel.config.js
  index.js
  jsconfig.json
  package-lock.json
  package.json
  src/controllers/list.controller.js
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/models/list.dao.js
  src/models/user.dao.js
  src/models/user.sql.js
  src/providers/list.provider.js
  src/providers/user.provider.js
  src/routes/user.route.js
  src/services/user.service.js
  swagger/user.swagger.yml
Labels: ✏️ FEAT

#13 [#6] Feat: url텍스트 요약 기능 구현
  .DS_Store
  index.js
  package-lock.json
  package.json
  src/controllers/link.controller.js
  src/dtos/link.dto.js
  src/models/link.dao.js
  src/models/link.sql.js
  src/providers/link.provider.js
  src/routes/link.route.js
  src/services/link.service.js
Labels: ✏️ FEAT

#18 [#7] Feat: zip 생성/삭제 구현
  index.js
  src/controllers/zip.controller.js
  src/dtos/zip.dto.js
  src/models/zip.dao.js
  src/models/zip.sql.js
  src/routes/zip.route.js
  src/services/zip.service.js
Labels: ✏️ FEAT

#20 [#14] Feat: Link 모든 기능 구현
  config/response.status.js
  index.js
  src/controllers/link.controller.js
  src/dtos/link.dto.js
  src/models/link.dao.js
  src/models/link.sql.js
  src/providers/link.provider.js
  src/routes/link.route.js
  src/services/link.service.js
  swagger/link.swagger.yml
Labels: ✏️ FEAT

#24 [#23] Feat: 최근저장/좋아요 리스트 구현
  src/controllers/list.controller.js
  src/dtos/list.dto.js
  src/models/list.dao.js
  src/models/list.sql.js
  src/providers/list.provider.js
  src/routes/list.route.js
  swagger/likelist.swagger.yml
  swagger/recentlist.swagger.yml
Labels: ✏️ FEAT

#27 [#15] Feat: 닉네임 중복 처리
  config/response.status.js
  index.js
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/models/user.dao.js
  src/models/user.sql.js
  src/providers/user.provider.js
  src/routes/user.route.js
  src/services/user.service.js
  swagger/user.swagger.yml
Labels: ✏️ FEAT

#29 [#28] Fix: 닉네임 중복 api 수정
  index.js
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/models/user.dao.js
  src/services/user.service.js
  swagger/user.swagger.yml
Labels: 🛠️ FIX

#30 [#19] Feat: Zip 조회기능 구현
  src/controllers/zip.controller.js
  src/dtos/zip.dto.js
  src/models/zip.dao.js
  src/models/zip.sql.js
  src/providers/zip.provider.js
  src/routes/zip.route.js
Labels: ✏️ FEAT
