Repository Link-zip/Link-zip-BE, pull requests merged in 2024-08, with the labels that each got.

#37 [#36] Refactor: Zip 조회 빠른저장 Zip 최우선순위 수정
  src/models/zip.dao.js
  src/models/zip.sql.js
Labels: ⚙️ REFACTOR

#39 [#33] Feat: 카카오 토큰 발급 및 jwt 생성
  .DS_Store
  config/error.js
  config/global.js
  config/response.status.js
  index.js
  package-lock.json
  package.json
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/models/user.dao.js
  src/models/user.sql.js
  src/providers/user.provider.js
  src/routes/user.route.js
  src/services/user.service.js
Labels: ✏️ FEAT

#44 Refactor 알림 코드 수정
  sql.sql
  src/controllers/alert.controller.js
  src/dtos/alert.dto.js
  src/models/alert.dao.js
  src/models/alert.sql.js
  src/routes/alert.route.js
  src/services/alert.service.js
  swagger/alertCreate.swagger.yml
  swagger/alertDlete.swagger.yml
  swagger/alertPreview.swagger.yml
Labels: ⚙️ REFACTOR

#49 [#46] Refactor: zip, 검색 swagger 작성 및 error status 추가, 코드 리팩터링
  config/response.status.js
  src/controllers/zip.controller.js
  src/dtos/zip.dto.js
  src/models/search.dao.js
  src/models/zip.dao.js
  src/providers/search.provider.js
  src/services/zip.service.js
  swagger/search.swagger.yml
  swagger/zip.swagger.yml
Labels: ⚙️ REFACTOR

#56 [#55] Refactor: 알림&리스트 swagger 수정 및 "code": "2000"으로 수정
  config/response.status.js
  swagger/alertConfirm.swagger.yml
  swagger/alertCreate.swagger.yml
  swagger/alertPreview.swagger.yml
  swagger/likelist.swagger.yml
  swagger/recentlist.swagger.yml
  swagger/unsightlist.swagger.yml
Labels: ⚙️ REFACTOR

#63 [#58] Refactor: 리스트 날짜 응답 형식 수정
  src/dtos/list.dto.js
Labels: ⚙️ REFACTOR

#59 [#52] Refactor: zip조회 응답 형식 변경, swagger 변경
  src/models/search.dao.js
  src/providers/search.provider.js
  src/providers/zip.provider.js
  swagger/zip.swagger.yml
Labels: ⚙️ REFACTOR

#64 [#57] Feat: 홈화면 기능 API 구현
  index.js
  src/controllers/linkscount.controller.js
  src/dtos/linkscount.dto.js
  src/models/linkscount.dao.js
  src/models/linkscount.sql.js
  src/providers/linkscount.provider.js
  src/routes/linkscount.route.js
  swagger/homeCount.swagger.yml
Labels: ✏️ FEAT

#66 [#65] Feat: 미확인 알림 여부 API 구현
  src/controllers/alert.controller.js
  src/dtos/alert.dto.js
  src/dtos/linkscount.dto.js
  src/models/alert.dao.js
  src/models/alert.sql.js
  src/routes/alert.route.js
  src/services/alert.service.js
  swagger/alertUncofirmExist.swagger.yml
Labels: ✏️ FEAT

#67 [#53] Feat : link sort
  src/controllers/link.controller.js
  src/dtos/link.dto.js
  src/dtos/notice.dto.js
  src/models/link.dao.js
  src/models/link.sql.js
  src/models/notice.dao.js
  src/services/link.service.js
  swagger/link.swagger.yml
  swagger/notice.swagger.yml
Labels: ✏️ FEAT, 📄 DOCS, ⚙️ REFACTOR

#69 [#61] Feat: 최근 검색어 기능 구현
  config/response.status.js
  index.js
  package-lock.json
  package.json
  src/controllers/search.controller.js
  src/models/search.dao.js
  src/models/zip.dao.js
  src/routes/search.route.js
  src/services/search.services.js
  swagger/search.swagger.yml
  swagger/zip.swagger.yml
Labels: ✏️ FEAT, ⚙️ REFACTOR, 🛠️ FIX

#71 [#70] Refactor: alert, list, home API 전반적인 코드 수정
  sql.sql
  src/dtos/alert.dto.js
  src/models/alert.dao.js
  src/models/linkscount.dao.js
  src/models/list.dao.js
  swagger/alert.swagger.yml
  swagger/alertConfirm.swagger.yml
  swagger/alertCreate.swagger.yml
  swagger/alertPreview.swagger.yml
  swagger/alertUncofirmExist.swagger.yml
  swagger/likelist.swagger.yml
  swagger/list.swagger.yml
  swagger/recentlist.swagger.yml
  swagger/unsightlist.swagger.yml
Labels: ⚙️ REFACTOR

#73 [#72] Feat: 회원가입 유저생성시 자동으로 default zip 생성 추가
  src/models/user.dao.js
  src/models/zip.sql.js
Labels: ✏️ FEAT

#75 [#74] Feat : 링크 생성 및 수정시 알림 데이터에도 적용
  src/models/link.dao.js
  src/models/link.sql.js
  src/services/link.service.js
Labels: ✏️ FEAT

#78 [#76] Feat: 닉네임 수정 및 형식 변환
  config/response.status.js
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/models/user.dao.js
  src/models/user.sql.js
  src/routes/user.route.js
  src/services/user.service.js
  swagger/user.swagger.yml
Labels: ✏️ FEAT

#80 [#79 ]Refactor: zip 삭제 관련 코드수정
  src/controllers/zip.controller.js
  src/dtos/zip.dto.js
  src/models/zip.dao.js
  src/models/zip.sql.js
  src/services/zip.service.js
Labels: ⚙️ REFACTOR

#82 [#81] Refactor: alert 오류 수정 및 쿼리 수정
  src/dtos/alert.dto.js
  src/models/alert.dao.js
  src/models/alert.sql.js
Labels: ⚙️ REFACTOR

#83 [#41] Feat: redis를 사용한 key, refresh token 관리
  config/authMiddleware.js
  config/redis.js
  config/response.status.js
  config/session.js
  index.js
  package-lock.json
  package.json
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/providers/user.provider.js
  src/services/user.service.js
  src/utils/jwt.util.js
  swagger/user.swagger.yml
Labels: ✏️ FEAT

#87 [#86] Refactor: 토큰 형식 수정
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/providers/user.provider.js
  src/services/user.service.js
  swagger/user.swagger.yml
Labels: ⚙️ REFACTOR

#88 [#84] Refactor: 리마인드 알림 생성 및 삭제
  src/models/link.dao.js
  src/models/link.sql.js
Labels: ⚙️ REFACTOR

#90 [#89] Refactor: 알림 관련 코드 수정
  package-lock.json
  src/dtos/alert.dto.js
  src/models/alert.dao.js
  src/models/alert.sql.js
  src/models/linkscount.sql.js
  src/models/list.dao.js
  src/services/link.service.js
  swagger/alert.swagger.yml
Labels: ⚙️ REFACTOR

#92 [#91] refactor: 링크 수정시 리마인드 알림 생성하는 코드 수정
  src/models/link.dao.js
  src/models/link.sql.js
Labels: ⚙️ REFACTOR

#94 [#93] Refactor: refresh token 로직 수정
  src/controllers/user.controller.js
Labels: ⚙️ REFACTOR
